# Generated by Django 2.1.7 on 2019-02-23 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_article_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='data',
            new_name='published',
        ),
    ]
