# Generated by Django 2.1.7 on 2019-02-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190223_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='num_articles',
            field=models.IntegerField(default=0),
        ),
    ]
