# Generated by Django 2.1.7 on 2019-02-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_category_num_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='num_articles',
        ),
        migrations.AlterField(
            model_name='article',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
    ]
