# Generated by Django 2.1.7 on 2019-02-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190224_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.DateField(default='2019-02-28'),
        ),
    ]
