# Generated by Django 2.1.7 on 2019-02-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
