# Generated by Django 2.1.7 on 2019-02-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_reply_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='published',
            field=models.DateField(default='2019-02-28'),
        ),
    ]
