# Generated by Django 2.1.7 on 2019-03-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_reply_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='was_read_by_manager',
            field=models.BooleanField(default=False),
        ),
    ]
