# Generated by Django 2.1.7 on 2019-03-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_comment_was_read_by_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_on_the_waiting_list',
            field=models.BooleanField(default=False),
        ),
    ]
