# Generated by Django 2.1.7 on 2019-03-04 20:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_comment_is_on_the_waiting_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateField(default=datetime.datetime(2019, 3, 4, 20, 36, 7, 352267, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='published',
            field=models.DateField(default=datetime.datetime(2019, 3, 4, 20, 36, 7, 352905, tzinfo=utc)),
        ),
    ]
