# Generated by Django 2.1.7 on 2019-03-04 20:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20190304_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateField(default=datetime.datetime(2019, 3, 4, 20, 37, 6, 692274, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
