# Generated by Django 2.1.7 on 2019-03-04 20:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20190304_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateField(default=datetime.datetime(2019, 3, 4, 20, 38, 0, 53881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='published',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
