# Generated by Django 2.1.7 on 2019-03-04 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20190304_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateField(default=datetime.datetime(2019, 3, 4, 20, 40, 29, 183118, tzinfo=utc)),
        ),
    ]
