# Generated by Django 2.1.7 on 2019-03-04 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20190304_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
