# Generated by Django 2.1.7 on 2019-03-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20190304_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='was_read_by_manager',
            field=models.BooleanField(default=False),
        ),
    ]
