# Generated by Django 2.1.7 on 2019-03-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_contact_was_read_by_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_id',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
